name: globe_trans_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  convex_bottom_bar: ^3.2.0
  intl: ^0.18.1
  shared_preferences: ^2.0.6
  image_picker: ^1.1.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  provider: ^6.1.2
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/logo.png
    - assets/kontaktfoto.jpeg
    - assets/statusfoto.jpg
    - assets/mertkontaktfoto.jpeg
    - assets/melekkontaktfoto.jpeg
    - assets/direnckontaktfoto.jpeg
    - assets/yelizkontaktfoto.jpeg
    - assets/flags/flag_turkey.png
    - assets/flags/flag_spain.png
    - assets/flags/flag_usa.png
    - assets/flags/flag_germany.png
    - assets/flags/flag_france.png
    - assets/flags/flag_canada.png
    - assets/flags/flag_belgium.png
    - assets/flags/flag_italy.png
    - assets/flags/flag_poland.png
    - assets/gif/Dennis_gif_kleiner.gif

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sfpro/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/sfpro/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/sfpro/SFPRODISPLAYLIGHTITALIC.OTF
          weight: 300
          style: italic
        - asset: assets/fonts/sfpro/SFPRODISPLAYBOLD.OTF

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/applogo.png
